### ISSUE TITLE
RTCGQ02LM not showing any data

### ISSUE THREAD

**Issue by xbmcnut** [dentra/esphome-components#1]
Hi there,

Thanks for the great integration. Like many I'm sure, I mistakenly purchased the bluetooth sensors instead of the Zigbee ones so I've been on a mission this weekend to get these connected. I've tried all the known methods to recover the bind key and the only one that worked was the hacked Mi Home app from the Russian site (version 6.1.701) which created a file on my Android device with the MAC, bind key and token.

I've added the following code below and amended my my MAC and extracted bind key but my ESP32 is not showing any data form the three entities. When adding your code verbatim, I'm also getting an error in ESPHome for the `timeout` and `idle_time` stating these are not valid options to I've removed those two lines so the code will compile. 

How do I check to see if ESPHome is at least 'talking' to my motion sensor 2?
```
external_components:
  - source: github://dentra/esphome-components

binary_sensor:
  - platform: miot_mccgq02hl
    # String (Required), device MAC-address.
    mac_address: "discovered-mac"
    # String, (Optional), device bind key
    bindkey: "discovered-bindkey-32"
    # String, (Optional), the name of binary sensor
    name: "RTCGQ02LM Motion Sensor 2"
    # BinarySensor (Optional), Light intensivity: on - strong light, off - weak light
    light:
      name: "RTCGQ02LM Light"
    # Sensor (Optional), Battey Level, %
    battery_level:
      name: "RTCGQ02LM Battery Level"
```
HA version core-2021.9.6
ESPHome version 2021.9.0
