### ISSUE TITLE
XMWSDJ04MMC - No battery level

### ISSUE THREAD

**Issue by cvjensen** [dentra/esphome-components#31]
Hi there , I have added this device in my esp config:

```
  - platform: miot_thermogigro
    mac_address: AA:BB:CC:DD:EE:FF
    bindkey: "1234567...."
    name: "E-ink Test Temperatur"
    humidity:
      name: "E-ink Test Fugtighed"
    battery_level:
      name: "E-ink Test Batteri"

  - platform: ble_rssi
    mac_address: AA:BB:CC:DD:EE:FF
    name: "E-ink Test signalstyrke"
    id: test_rssi
```

Everything seems fine except the battery data:

![image](https://user-images.githubusercontent.com/9024493/195976415-bd1dff28-4dad-46ca-84b4-3038759e3ff6.png)

How can that be ?
