### ISSUE TITLE
missing file  while compiling esphome-components/components/crash_info/

### ISSUE THREAD

**Issue by HelixX23** [dentra/esphome-components#33]
Hi,
i am using ESPHome in Home Assistant OS
while compiling i get this message:
`crash_info.cpp:1:28: fatal error: user_interface.h: No such file or directory`

here is the part of the ESPHome device yaml:

```
####
# Crash Info
#  An ESP8266 remote crash detector. With enabled indicator you can monitor crashes right from your Home Assistant.
# https://github.com/dentra/esphome-components/tree/master/components/crash_info
####
external_components:
  - source:
      type: local
      path: my_custom_components/crash_info

crash_info:
  id: crash_info_obj
  # Optional, uint32. The number of stack frames to be saved.
  max_stack_frames_size: 10
  # Optional, uint32. Minimum address of stack frame to be saved. Default: 0x40000000.
  min_stack_frames_addr: 0x40000000
  # Optional, uint32. Maximum address of stack frame to be saved. Default: 0x50000000.
  max_stack_frames_addr: 0x50000000
  # Optional, binary_sensor. Crash indicator.
  indicator:
    name: $friendly_devicename Crash state
  # Optional, boolean. Store backtrace in FLASH or RTC. Default: false.
  store_in_flash: false

# Add button to reset state of crash.
button:
  - platform: template
    name: $friendly_devicename Reset crash state
    on_press:
      lambda: id(crash_info_obj).reset();

# Add sntp or homeassistant time platform to enable saving crash time.
time:
  - platform: homeassistant
    id: homeassistant_time
```

where can i find the user_interface.h file which is included in line 1 of crash_info.cpp file?
