### ISSUE TITLE
add weekday to energy tariffs 

### ISSUE THREAD

**Issue by wazoo666** [dentra/esphome-components#39]
Hi
It is possible to add "weekday"  and "holiday" to tariffs component ??  :)

I mean, actually in Spain PVPC has 3 tariff , like P1 for peak (expensive), P2 for mid and P3 for valley (cheap)
but they are separated in weekday too
I mean, P1, P2 and P3 are used for working days (mon-fri),  buy (sat-sun) are 24h all same P3 tariff
and to complicate this situation it adds national holidays that always are P3  (12 days over the year)
ThankU

**Comment by dentra** [comment]
do you mean something like this:
```yaml
...
      - name: "P1"
        time: "06:00-14:00"
        days_of_week: &workdays MON-FRI
        exclude: &holidays [25.12, 26.12, 27.12]
      - name: "P2"
        time: "14:00-22:00"
        days_of_week: *workdays
        exclude: *holidays
      - name: "P3"
...
```
