### ISSUE TITLE
Energy Tariffs Component

### ISSUE THREAD

**Issue by Roving-Ronin** [dentra/esphome-components#59]
Hi @dentra,

Thanks for these components, using the Energy Statistic component with my Athom v2 and v3 plugs and it works quite well.
When using webserver version = 3, with its ability to allow defining the sort order of sensors, it comes out as:

![image](https://github.com/user-attachments/assets/1bd56385-ef2e-4c20-94f1-8c0c3c5ccbd5)

Just having a play and looking to see if the Energy Tariffs component would be useful, but trying to work out if it can support the tariff plans we have in Australia. Leaving out the new 'Peak Demand' tariffs being introduced to the market, we have the following 'Time of Use' TOU plans that are typically:

Monday - Friday:
 Peak - 7am to 9am
 Shoulder - 9am to 5pm
 Peak - 5pm to 8pm
 Shoulder - 8pm to 10pm
 Off Peak - 10pm to 7am

Saturday and Sundays:
 Off Peak - All Day/Night (i.e. from 10pm Friday to 7am Monday)

Is your Tariff component able to support these tariffs, or does the component currently only support defining the time but not allow specifying the day also ?

Many Thanks !

**Comment by Roving-Ronin** [comment]
Ooops... I should have checked closed issues first. Just noticed this old issue:  https://github.com/dentra/esphome-components/issues/39

```
      - name: "P1"
        time: "06:00-14:00"
        days_of_week: &workdays MON-FRI
        exclude: &holidays [25.12, 26.12, 27.12]
      - name: "P2"
        time: "14:00-22:00"
        days_of_week: *workdays
        exclude: *holidays
      - name: "P3"
```

Is there a version of the component that has the days_of_week functionality added to it that I can test? Looking at the C+ code I can't find any reference to this in the 'Master' branch version.

Thanks.

**Comment by dentra** [comment]
#39 it is not implemented, but only proposed. If it fits, then I'll try to implement it.

**Comment by Roving-Ronin** [comment]
Happy to test it, if you implement it ! ;-)
BTW where are the 'workdays' / 'holidays' / 'weekends' defined, or is that pulled from HomeAssistant and the WorkDay integration?

**Comment by Roving-Ronin** [comment]
Looking at this component and its perfect to convert to provide a 'Water Statistics' also. Only issue is that in sensor.py it refers to kWh:

```
from esphome.const import (
    CONF_ID,
    CONF_TIME_ID,
    CONF_POWER,
    CONF_TOTAL,
    DEVICE_CLASS_ENERGY,
    STATE_CLASS_TOTAL_INCREASING,
    UNIT_KILOWATT_HOURS,
)
```
would you have any idea how to change the units to litres and it appears that esphome.const doesn't include this?

TIA.

**Comment by dentra** [comment]
Is just setting unit_of_measurenent doesn't work?

**Comment by Roving-Ronin** [comment]
Yes, I was having a go at it and that was where it failed. Have a look at: https://github.com/Roving-Ronin/myHomeAssistant/tree/main/components/water_statistics

If you want to copy that over to your repository and I'll delete my attempt, please do as it's your code and credit.

Looking at this, if cubic meters (m3) and megajoules (MJ) could also be supported, this would also allow you to publish a 'Gas Statistics (m3)' and 'Gas Statistics (MJ)' component also, so you'd have Energy, Gas and Water covered :-)
Anyone using MJ would need to be aware most utility companies update their 'Pressure Factor' and Heating Value' that is used to calculate m3 into MJ, and include a sensor for this in their ESPHome device that they update quarterly. i.e.

```

  - platform: template
    name: "Gas - Consumed (MJ)"
    id: gas_consumed_mj
    unit_of_measurement: "MJ"
    device_class: energy
    state_class: "total_increasing"
    icon: "mdi:counter"
    accuracy_decimals: 3   
    # With EACH QUARTERLY GAS BILL update the Jemena Pressure Factor and Heating Value below.   
    # Formula - (Gas Consumed x Pressure Factor x Heating Value) = Usage MJ
    lambda: |-
      return (id(gas_consumed_m3).state * 0.9864 * 37.98);
    update_interval: 1s
    filters:
      - delta : 0.001
```

BTW any luck looking at adding 'Energy - Year' to Statistics or adding the days of week to Tariffs ( https://github.com/dentra/esphome-components/issues/39 ) ? Thanks !
