### ISSUE TITLE
esphome-components/components /backup documentation improvement

### ISSUE THREAD

**Issue by noseshimself** [dentra/esphome-components#63]
As the component is depending on the local web server there should be a warning that the required authentication is *not* whatever has been set in

```
backup:
  auth:
    username: !secret config_download_username
    password: !secret config_download_password
```
 but whatever has been set in ``web_server``.
