### ISSUE TITLE
Compiling error for energy statistics - std::isnan

### ISSUE THREAD

**Issue by poldim** [dentra/esphome-components#7]
Hey,

Thanks for publishing this.  I'm trying to use this with a Sonoff S31.  Your example assumes the device provides a total energy sensor but this device does not.  I'm hoping I can just use the integral sensor of the power to accomplish this.  But when I try to compile on the latest dev version of esphome, it fails with the following error:

```c++
Processing esphome_garage_controls_s31 (board: esp01_1m; framework: arduino; platform: platformio/espressif8266 @ 2.6.2)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 1MB Flash
PACKAGES: 
 - framework-arduinoespressif8266 3.20704.0 (2.7.4) 
 - tool-esptool 1.413.0 (4.13) 
 - tool-esptoolpy 1.20800.0 (2.8.0) 
 - toolchain-xtensa 2.40802.200502 (4.8.2)
Library Manager: Installing Update
Library Manager: Already installed, built-in library
Dependency Graph
|-- <ESPAsyncTCP-esphome> 1.2.3
|   |-- <ESP8266WiFi> 1.0
|-- <ESPAsyncWebServer-esphome> 1.3.0
|   |-- <ESPAsyncTCP-esphome> 1.2.3
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <Hash> 1.0
|   |-- <ESP8266WiFi> 1.0
|   |-- <ArduinoJson-esphomelib> 5.13.3
|-- <ESP8266WiFi> 1.0
|-- <ArduinoJson-esphomelib> 5.13.3
|-- <ESP8266mDNS> 1.2
|   |-- <ESP8266WiFi> 1.0
|-- <noise-c> 0.1.3
|   |-- <libsodium> 1.10018.1
|-- <DNSServer> 1.1.1
|   |-- <ESP8266WiFi> 1.0
Compiling .pioenvs/esphome_garage_controls_s31/src/esphome/components/energy_statistics/energy_statistics.cpp.o
src/esphome/components/energy_statistics/energy_statistics.cpp: In member function 'virtual void esphome::energy_statistics::EnergyStatistics::loop()':
src/esphome/components/energy_statistics/energy_statistics.cpp:51:18: error: 'isnan' was not declared in this scope
   if (isnan(total)) {
                  ^
src/esphome/components/energy_statistics/energy_statistics.cpp:51:18: note: suggested alternative:
In file included from src/esphome/core/component.h:5:0,
                 from src/esphome/components/energy_statistics/energy_statistics.h:3,
                 from src/esphome/components/energy_statistics/energy_statistics.cpp:2:
/config/.esphome/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/4.8.2/cmath:632:5: note:   'std::isnan'
     isnan(_Tp __x)
     ^
src/esphome/components/energy_statistics/energy_statistics.cpp: In member function 'void esphome::energy_statistics::EnergyStatistics::process_(float)':
src/esphome/components/energy_statistics/energy_statistics.cpp:78:62: error: 'isnan' was not declared in this scope
   if (this->energy_today_ && !isnan(this->energy_.start_today)) {
                                                              ^
src/esphome/components/energy_statistics/energy_statistics.cpp:78:62: note: suggested alternative:
In file included from src/esphome/core/component.h:5:0,
                 from src/esphome/components/energy_statistics/energy_statistics.h:3,
                 from src/esphome/components/energy_statistics/energy_statistics.cpp:2:
/config/.esphome/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/4.8.2/cmath:632:5: note:   'std::isnan'
     isnan(_Tp __x)
     ^
src/esphome/components/energy_statistics/energy_statistics.cpp:82:70: error: 'isnan' was not declared in this scope
   if (this->energy_yesterday_ && !isnan(this->energy_.start_yesterday)) {
                                                                      ^
src/esphome/components/energy_statistics/energy_statistics.cpp:82:70: note: suggested alternative:
In file included from src/esphome/core/component.h:5:0,
                 from src/esphome/components/energy_statistics/energy_statistics.h:3,
                 from src/esphome/components/energy_statistics/energy_statistics.cpp:2:
/config/.esphome/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/4.8.2/cmath:632:5: note:   'std::isnan'
     isnan(_Tp __x)
     ^
src/esphome/components/energy_statistics/energy_statistics.cpp:86:60: error: 'isnan' was not declared in this scope
   if (this->energy_week_ && !isnan(this->energy_.start_week)) {
                                                            ^
src/esphome/components/energy_statistics/energy_statistics.cpp:86:60: note: suggested alternative:
In file included from src/esphome/core/component.h:5:0,
                 from src/esphome/components/energy_statistics/energy_statistics.h:3,
                 from src/esphome/components/energy_statistics/energy_statistics.cpp:2:
/config/.esphome/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/4.8.2/cmath:632:5: note:   'std::isnan'
     isnan(_Tp __x)
     ^
src/esphome/components/energy_statistics/energy_statistics.cpp:90:62: error: 'isnan' was not declared in this scope
   if (this->energy_month_ && !isnan(this->energy_.start_month)) {
                                                              ^
src/esphome/components/energy_statistics/energy_statistics.cpp:90:62: note: suggested alternative:
In file included from src/esphome/core/component.h:5:0,
                 from src/esphome/components/energy_statistics/energy_statistics.h:3,
                 from src/esphome/components/energy_statistics/energy_statistics.cpp:2:
/config/.esphome/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/4.8.2/cmath:632:5: note:   'std::isnan'
     isnan(_Tp __x)
     ^
*** [.pioenvs/esphome_garage_controls_s31/src/esphome/components/energy_statistics/energy_statistics.cpp.o] Error 1
========================== [FAILED] Took 4.35 seconds ==========================
```

Relevant config:
```yaml
external_components:
### https://github.com/dentra/esphome-components/
  - source:
      type: git
      url: https://github.com/dentra/esphome-components
    components: 
    - energy_statistics


sensor:
- platform: integration
  name: "${friendly_name} Total Energy"
  id: total_energy_by_integration
  sensor: s31_power
  time_unit: h
  unit_of_measurement: "kWh"
  filters:
    - multiply: 0.001
  accuracy_decimals: 3
  restore: true
  state_class: total_increasing


- platform: "energy_statistics"
  total: total_energy_by_integration
  energy_today:
    name: "${friendly_name} Energy Today"
  energy_yesterday:
    name: "${friendly_name} Energy Yesterday"
  energy_week:
    name: "${friendly_name} Energy Week"
  energy_month:
    name: "${friendly_name} Energy Month"


- platform: cse7766
  update_interval: 10s
  current:
    name: "${friendly_name} Current"
  voltage:
    name: "${friendly_name} Voltage"
  power:
    name: "${friendly_name} Power"
    id: s31_power
    unit_of_measurement: W
    filters:
      - delta: 3.0
    on_value:
      then:
        - sensor.template.publish:
            id: s31_power_kw
            state: !lambda '{ return x; }'
- platform: template
  name: "${friendly_name} in kW"
  id: s31_power_kw
  internal: true
  filters:
    - delta: 5
    - debounce: 5s
    - multiply: 0.001
  unit_of_measurement: "kW"
  accuracy_decimals: 3
```
